[package]
name = "transfer-role-features-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.transfer-role-features]
path = ".."

[dependencies.drt-sc-meta]
version = "0.0.1-patch1"
path = "../../../../../framework/meta"
