[package]
name = "rust-interact"
version = "0.0.0"
authors = ["xfactor@toml <xfactor.toml@gmail.com>", "Sumanth <saisumanthvadla@gmail.com>"]
edition = "2021"
publish = false

[[bin]]
name = "rust-interact"
path = "src/lib.rs"

[dependencies.rust-snippets-generator-test]
path = ".."

[dependencies.drt-sc-snippets]
version = "0.0.1-patch1"
path = "../../../../framework/snippets"

[dependencies.drt-sc-scenario]
version = "0.0.1-patch1"
path = "../../../../framework/scenario"

[dependencies.drt-chain-vm]
version = "0.1.2"
path = "../../../../vm"

[dependencies.drt-sdk]
version = "0.0.1-patch1"
path = "../../../../sdk/core"

[workspace]


