[package]
name = "transfer-role-features"
version = "0.0.0"
authors = ["xfactor@toml <xfactor.toml@gmail.com>", "Sumanth <saisumanthvadla@gmail.com>"]
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[dev-dependencies.vault]
path = "../vault"

[dependencies.drt-sc]
version = "0.0.1-patch1"
path = "../../../../framework/base"

[dependencies.drt-sc-modules]
version = "0.0.1-patch1"
path = "../../../../contracts/modules"

[dev-dependencies.drt-sc-scenario]
version = "0.0.1-patch1"
path = "../../../../framework/scenario"
