[package]
name = "parent-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.parent]
path = ".."

[dependencies.drt-sc]
version = "0.0.1-patch1"
path = "../../../../../../framework/base"

[dependencies.drt-sc-meta]
version = "0.0.1-patch1"
path = "../../../../../../framework/meta"
