[package]
name = "digital-cash-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.digital-cash]
path = ".."

[dependencies.drt-sc-meta]
version = "0.0.1-patch1"
path = "../../../../framework/meta"
