[package]
name = "panic-message-features-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.panic-message-features]
path = ".."

[dependencies.drt-sc-meta]
version = "0.0.1-patch1"
path = "../../../../framework/meta"
