[package]
name = "proxy-test-first-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.proxy-test-first]
path = ".."

[dependencies.drt-sc-meta]
version = "0.0.1-patch1"
path = "../../../../../framework/meta"
