// Code generated by the drt-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            6
// Async Callback (empty):               1
// Total number of exported functions:   8

#![no_std]
#![feature(alloc_error_handler, lang_items)]

drt_sc_wasm_adapter::allocator!();
drt_sc_wasm_adapter::panic_handler!();

drt_sc_wasm_adapter::endpoints! {
    dcdt_transfer_with_fee
    (
        setExactValueFee
        setPercentageFee
        claimFees
        transfer
        getTokenFee
        getPaidFees
    )
}

drt_sc_wasm_adapter::empty_callback! {}
