[package]
name = "test-gen"
version = "0.0.0"
authors = ["xfactor@toml <xfactor.toml@gmail.com>", "Sumanth <saisumanthvadla@gmail.com>"]
edition = "2021"

[[bin]]
name = "test-gen"
path = "src/test_gen.rs"

[dependencies]
