[package]
name = "proxy-test-first"
version = "0.0.0"
authors = ["xfactor@toml <xfactor.toml@gmail.com>", "Sumanth <saisumanthvadla@gmail.com>"]
edition = "2021"
publish = false

[lib]
path = "src/proxy-test-first.rs"

[features]
ei-unmanaged = ["drt-sc/ei-unmanaged"]

[dependencies]
hex-literal = "0.3.1"

[dependencies.drt-sc]
version = "0.0.1-patch1"
path = "../../../../framework/base"
features = ["alloc"]

[dependencies.drt-sc-wasm-adapter]
version = "0.0.1-patch1"
path = "../../../../framework/wasm-adapter"
optional = true

[dev-dependencies.drt-sc-scenario]
version = "0.0.1-patch1"
path = "../../../../framework/scenario"
